### ISSUE TITLE
I can't get user photo_url and some user's first name

### ISSUE THREAD

**Issue by farshid-shokrolahi** [khamidjon-khamidov/flutter_telegram_web_app#2] opened 2024-06-09 10:31 UTC
Hi there.
Thank you for your great package.

There is no `photo_url` in `initData.user` and when I use `initDataUnsafe?.user?.photo_url` I get a null value. 
Also for some users, the `first_name` is null. and I know they have first name in their telegram accounts.

Please let me know if I did something wrong.
Thanks

**Comment by khamidjon-khamidov** [comment] 2024-06-09 12:21
Hi @farshid-shokrolahi . Thanks for opening the issue). According to the [documentation](https://core.telegram.org/bots/webapps#webappinitdata) photo url is "Optional. URL of the user’s profile photo. The photo can be in .jpeg or .svg formats. Only returned for Mini Apps launched from the attachment menu.". The user should open the bot from attachment menu which is currently available for advertisers or test env.

Regarding first_name, I cannot reproduce the issue. You should check if they entered their full name to only one field (first name or last name).

**Comment by khamidjon-khamidov** [comment] 2024-07-03 16:16
@farshid-shokrolahi I will close this task if I don't get any updates from you

**Closed** 2024-07-04 07:11 UTC
